@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.scalinghealth.loot.conditions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;