@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.scalinghealth.loot.conditions;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;