@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.scalinghealth.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;