@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.scalinghealth.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;