@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.scalinghealth.client.render.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;